### PR TITLE
Mibbit -> Slack Migration

### PR DESCRIPTION
**Pull request by mbillow**
Let do this on the repository that matters now...

### CODE REVIEW

**Comment by bencentra** [comment]
:+1: 

For this repo and bootstrap-csh, I should just make the CSH org the actual owners. CSH having the forked copy is confusing.

**Comment by mbillow** [comment]
Truth.

**Comment by jeid64** [comment]
Truth.

**Comment by bencentra** [comment]
Error when I just tried to do it: "ComputerScienceHouse/bootstrap-csh already exists".

I think we have to delete the CSH forks first. Might mess up any projects that submodule'd them in.

Thoughts?

**Comment by harlanhaskins** [comment]
The answer to this is to make a CSHDN where we host the bootstrap theme.

**Comment by bencentra** [comment]
I could also set these up on Bower or something. Not as ideal as a CDN, but better than submodules.

**Comment by AndrewHanes** [comment]
I'm not sure you'll run into issues with submodules.  It might just use the new repo because it'll be at the same url.  It might be worth fixing it anyhow.  Deal with the issue in the short term to avoid the issue later if it even becomes one.

**Pull request merged**
